### ISSUE TITLE
ImportError: cannot import name 'Roku' from 'roku'

### ISSUE THREAD

**Issue by Phantom3** [jcarbaugh/python-roku#94]
Not sure what happened. Was working fine then today I get

Traceback (most recent call last):
  File "/home/pi/scripts/power-off.py", line 1, in <module>
    from roku import Roku
  File "/home/pi/.local/lib/python3.7/site-packages/roku/__init__.py", line 1, in <module>
    from roku.core import (  # noqa
  File "/home/pi/.local/lib/python3.7/site-packages/roku/core.py", line 1, in <module>
    import logging
  File "/usr/lib/python3.7/logging/__init__.py", line 26, in <module>
    import sys, os, time, io, traceback, warnings, weakref, collections.abc
  File "/usr/lib/python3.7/traceback.py", line 5, in <module>
    import linecache
  File "/usr/lib/python3.7/linecache.py", line 11, in <module>
    import tokenize
  File "/usr/lib/python3.7/tokenize.py", line 33, in <module>
    import re
  File "/home/pi/scripts/re.py", line 1, in <module>
    from roku import Roku
ImportError: cannot import name 'Roku' from 'roku' (/home/pi/.local/lib/python3.7/site-packages/roku/__init__.py)

tried to uninstall with pip and tried different versions.

**Comment by Phantom3** [comment]
Figured out what happened. Named a file re.py, it didn't like that. Renamed it and all works again
